---
- name: Install PHP
  apt: 
    name: "php{{ php_version }}"
    state: present

- name: Install PHP extensions
  apt:
    name: "{{ extension }}"
    state: present
  loop: "{{ php_extensions }}"
  loop_control:
    loop_var: extension
