---
- name: Download Wordpress
  unarchive:
      src: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
      dest: "/var/www/html/"
      remote_src: yes

- name: Create Wordpress Database
  template:
      src: mysql_config.sql
      dest: /tmp/mysql_config.sql
      owner: root
      group: root
      mode: '0644'
- name: Create Wordpress Database
  raw: mysql < /tmp/mysql_config.sql
  ignore_errors: yes
- name: Clean up MySQL-config file
  file:
      path: /tmp/mysql_config.sql
      state: absent

- name: Provide Wordpress-Config
  template:
      src: wp-config.php
      dest: /var/www/html/wordpress/wp-config.php
      owner: nobody
      group: nogroup
      mode: '0644'

