---
# This playbook requires --extra-vars: mysql_user and mysql_password
- hosts: 
  - servers
  remote_user: "{{remote_user}}"
  become: true
  gather_facts: false
  roles:
      - apt-update
      - apache2
      - php
      - mysql
      - phpmyadmin
