---
# This playbook requires --extra-vars: server_admin (an email address)
- hosts: 
  - servers
  remote_user: "{{remote_user}}"
  become: true
  gather_facts: false
  roles:
      - ssl-selfsigned

