---

- name: Install MySQL
  apt: name=mysql-server state=present

# TODO: Consider adding one of these
# - name: Removes anonymous user account for localhost
#   community.mysql.mysql_user:
#     name: ''
#     host: localhost
#     state: absent
#     login_unix_socket: /run/mysqld/mysqld.sock
# - name: Removes all anonymous user accounts
#   community.mysql.mysql_user:
#     name: ''
#     host_all: true
#     state: absent

- name: Install Python package pymysql.
  pip:
    name: pymysql
    # TODO: Necessary for Ubuntu versions 23 or newer, but there
    # might be more elegant ways to deal with this.
    extra_args: "{{ '--break-system-packages' if ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version'] == '23' else '' }}"

- name: Create database user.
  community.mysql.mysql_user:
    name:     "{{ database_username }}"
    password: "{{ database_password }}"
    # TODO: Consider using this along with a hashed password.
    # encrypted: true
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
    # TODO: Some other options to consider:
    # host: localhost
    # host_all: true
  when: database_username

- name: Create database.
  community.mysql.mysql_db:
    name: "{{ database_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
  when: database_name
