---
# TODO: feature/fix-mysql

- name: Install MySQL
  apt: name=mysql-server state=present

- name: Template MySQL-file for users
  template:
    src: mysql-config.sql
    dest: /tmp/mysql-config.sql
    owner: root
    group: root
    mode: '0644'

- name: Run MySQL-configuration for users
  raw: mysql < /tmp/mysql-config.sql
  ignore_errors: yes

- name: Clean up MySQL-config file
  file:
    path: /tmp/mysql-config.sql
    state: absent
