---

- name: Install MySQL
  apt: name=mysql-server state=present

- name: Template MySQL-file for users
  template:
      src: mysql_config.sql
      dest: /tmp/mysql_config.sql
      owner: root
      group: root
      mode: '0644'

- name: Run MySQL-configuration for users
  raw: mysql < /tmp/mysql_config.sql
  ignore_errors: yes

- name: Clean up MySQL-config file
  file:
      path: /tmp/mysql_config.sql
      state: absent
