---
- name: Download Wordpress
  unarchive:
    src: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
    dest: "/var/www/html/"
    remote_src: yes

# TODO: feature/fix-mysql
- name: Create Wordpress Database
  template:
    src: mysql-config.sql
    dest: /tmp/mysql-config.sql
    owner: root
    group: root
    mode: '0644'
- name: Create Wordpress Database
  raw: mysql < /tmp/mysql-config.sql
  ignore_errors: yes
- name: Clean up MySQL-config file
  file:
    path: /tmp/mysql-config.sql
    state: absent

# TODO: feature/fix-secrets
- name: Provide WordPress config.
  template:
    # TODO: Also beware of the likely security vulnerability we create by not providing
    # the WP_AUTH variables.
    src: wp-config.php
    dest: /var/www/html/wordpress/wp-config.php
    owner: nobody
    group: nogroup
    mode: '0644'

- name: Give wp-content/ to www-data, so that it can install themes and plugins
  file:
    path: /var/www/html/wordpress/wp-content/
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

# TODO: feature/fix-apache
- name: Make Apache point to wordpress directory
  lineinfile:
    path: '/etc/apache2/sites-available/{{ item }}'
    regexp: 'DocumentRoot '
    line: 'DocumentRoot /var/www/html/wordpress'
    backrefs: yes
  loop:
    - 000-default-le-ssl.conf
    - 000-default.conf
    - default-ssl.conf
  ignore_errors: yes

- name: Restart Apache
  service:
    name: apache2
    state: reloaded
