---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: "Include standard Ansible role"
      include_role:
        name: "{{ item }}"
      loop:
        - apt-update
        - php

    - name: Conditionally include fail2ban role
      include_role:
        name: fail2ban
      when: not insecure_skip_fail2ban
