---
- hosts: all
  become: true
  gather_facts: false
  roles:
    - apt-update
    - apache2
    - php
    - pip
    - mysql
    # TODO: feature/fix-apache
    - wordpress
    - apache-document-root
