---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - include_role:
        name: "{{ item }}"
      loop:
        - apt-update
        - apache2
        - php
        - pip
        - mysql
        - "{{ 'wordpress-manual' if wordpress_manual_install else 'wordpress-cli' }}"

    - include_role:
        name: ssl-selfsigned
      when: ssl_selfsigned

    # It's important that this runs after the selfsigned certificates,
    # if those are being used, but before Certbot, if that's being used.
    - include_role:
        name: apache-vhosts

    - include_role:
        name: ssl-certbot
      when: ssl_certbot

    - pause:
        minutes: 5
        prompt: "Please navigate to your site right now to complete the 'Famous 5 Minute WordPress Installation'. This is required for the next step of the script to suceed (setting some configurations in the database), and it's also important for security reasons that you do this right away. Keeping in line with WordPress tradition, you have exactly 5 minutes to complete this step. (Also, please don't interrupt this step with Ctrl+C, because Ansible Runner has some issues with handling KeyboardInterrupts - see https://github.com/ansible/ansible-runner/issues/756 or also their issue 1075."
      when: ssl_certbot and wordpress_manual_install

    - include_role:
        name: domain-for-wordpress
      when: ssl_certbot

    - include_role:
        name: apache-conf
      when: ssl_selfsigned

    - include_role:
        name: wordpress-block-xmlrpc
      when: not wordpress_insecure_allow_xmlrpc

    - include_role:
        name: fail2ban
      when: not insecure_skip_fail2ban
