---

# TODO: Maybe no longer necessary because of WP-CLI.
- name: Provide Wordpress with the URL
  community.mysql.mysql_query:
    login_db: "{{ database_name }}"
    query: "UPDATE {{ database_table_prefix }}options SET option_value = %s WHERE option_name IN ('siteurl', 'home')"
    positional_args:
      - "http://{{ wordpress_url }}"
    login_unix_socket: /run/mysqld/mysqld.sock
  ignore_errors: true
