---
# TODO: feature/fix-mysql
- name: Provide Wordpress with the URL
  template:
    src: wp.sql
    dest: /tmp/wp.sql
    owner: root
    group: root
    mode: '0644'
- name: Provide Wordpress with the URL
  raw: mysql < /tmp/wp.sql
- name: Clean up MySQL-file
  file:
    path: /tmp/wp.sql
    state: absent

# TODO: feature/fix-apache
- name: Make Apache point to wordpress directory
  lineinfile:
    path: '/etc/apache2/sites-available/{{ item }}'
    regexp: 'DocumentRoot '
    line: 'DocumentRoot /var/www/html/wordpress'
    backrefs: yes
  loop:
    - 000-default-le-ssl.conf
    - 000-default.conf
    - default-ssl.conf
  ignore_errors: yes

- name: Restart Apache
  service:
    name: apache2
    state: reloaded
