---
- name: Provide Wordpress with the URL
  template:
      src: wp.sql
      dest: /tmp/wp.sql
      owner: root
      group: root
      mode: '0644'


- name: Provide Wordpress with the URL
  raw: mysql < /tmp/wp.sql

- name: Clean up MySQL-file
  file:
      path: /tmp/wp.sql
      state: absent

- name: Make Apache point to wordpress directory
  lineinfile:
      path: /etc/apache2/sites-available/000-default-le-ssl.conf
      regexp: 'DocumentRoot '
      line: 'DocumentRoot /var/www/html/wordpress'
      backrefs: yes

- name: Restart Apache
  service:
      name: apache2
      state: reloaded
