---
- name: Install Apache
  apt: name=apache2 state=present

- name: Start Apache
  service: name=apache2 state=started enabled=yes

- name: Enable Apache module SSL
  raw: a2enmod ssl
  when: ssl_certbot or ssl_selfsigned
- name: Enable Apache module headers
  raw: a2enmod headers
  when: ssl_certbot or ssl_selfsigned

- name: Set Apache envvars if we have them
  lineinfile:
    path: /etc/apache2/envvars
    line: "export {{ key_eq_val }}"
    state: present
  loop: "{{ extra_env_vars }}"
  loop_control:
    loop_var: key_eq_val

- name: Reload Apache
  service: name=apache2 state=reloaded
