---

- name: Block the insecure endpoint xmlrpc.php
  template:
    src: .htaccess
    dest: "{{ apache_document_root }}/.htaccess"
    owner: nobody
    group: nogroup
    mode: '0644'

- name: Restart Apache
  service:
    name: apache2
    state: reloaded
